### ISSUE TITLE
Merge of Autoconfig not as expected

### ISSUE THREAD

**Issue by Fresher14** [Toroid-io/vcd2wavedrom#14]
Try this .vcd and look at porb: it should not be a pulse

$comment
TOOL:	simvision(64)	20.11-a001
$end

$date
    Apr 27, 2021 15:09:13
$end

$timescale
    0.01fs
$end

$scope module testbench $end

$scope module soc $end

$scope module infra $end

$scope module dut $end
$var wire 1 ! ASYNC_DISABLE $end
$var wire 1 " SCAN_ENABLE $end
$var wire 1 # can_event $end
$var wire 1 $ deepsleep_req $end
$var wire 1 % hvi_event $end
$var wire 1 & lin_event $end
$var wire 1 ' osc_rc_en $end
$var wire 1 ( osc_rc_ready $end
$var wire 1 ) otpc_boot_done $end
$var wire 1 * otpc_boot_req $end
$var wire 1 + otpc_nrsta $end
$var wire 1 , pmc_fpm_ready $end
$var wire 1 - pmc_lf_clk $end
$var wire 1 . pmc_lpm_en $end
$var wire 1 / pmc_vdd_off_in_lpm $end
$var wire 1 0 reset_inb $end
$var wire 1 1 rst_drive $end
$var wire 1 2 sleep_req $end
$var wire 1 3 software_rst_req $end
$var wire 1 4 spi_event $end
$var wire 1 5 system_rst_b $end
$var wire 1 6 vdig15_porb $end
$var wire 1 7 vdig15_resetb $end
$var wire 1 8 watchdog_rst_req $end
$var wire 1 9 wuc_lp_mode_entry $end
$var wire 1 : wuc_sm_error_flag $end
$upscope $end

$upscope $end

$upscope $end

$upscope $end

$enddefinitions $end
#0
$dumpvars
0!
0"
0#
0$
0%
0&
0'
0(
0)
0*
0+
1,
0-
0.
0/
00
11
02
03
04
05
06
07
08
09
0:
$end
#60000000000
16
#110000000000
17
#1000000000000
1-
#1500000000000
0-
#2000000000000
1-
#2500000000000
0-
#3000000000000
1-
#3500000000000
0-
#4000000000000
1-
#4500000000000
0-
#5000000000000
1-
01
10
#5500000000000
0-
#6000000000000
1-
#6500000000000
0-
#7000000000000
1-
#7500000000000
0-
#8000000000000
1-
1'
#8135119400000
1(
#8500000000000
0-
#9000000000000
1-
#9500000000000
0-
#10000000000000
1-
#10500000000000
0-
#11000000000000
1-
15
1+
#11500000000000
0-
#12000000000000
1-
1*
#12500000000000
0-
#13000000000000
1-
#13500000000000
0-
#14000000000000
1-
#14500000000000
0-
#15000000000000
1-
#15500000000000
0-
#16000000000000
1-
#16500000000000
0-
#17000000000000
1-
#17500000000000
0-
#18000000000000
1-
#18500000000000
0-
#19000000000000
1-
#19500000000000
0-
#20000000000000
1-
#20500000000000
0-
#21000000000000
1-
#21500000000000
0-
#22000000000000
1-
#22500000000000
0-
#23000000000000
1-
#23500000000000
0-
#24000000000000
1-
#24500000000000
0-
#25000000000000
1-
#25500000000000
0-
#26000000000000
1-
#26500000000000
0-
#27000000000000
1-
#27500000000000
0-
#28000000000000
1-
#28500000000000
0-
#29000000000000
1-
#29500000000000
0-
#30000000000000
1-
#30500000000000
0-
#31000000000000
1-
#31500000000000
0-
#32000000000000
1-
#32500000000000
0-
#33000000000000
1-
#33500000000000
0-
#34000000000000
1-
#34500000000000
0-
#35000000000000
1-
#35500000000000
0-
#36000000000000
1-
#36500000000000
0-
#37000000000000
1-
#37500000000000
0-
#38000000000000
1-
#38500000000000
0-
#39000000000000
1-
#39500000000000
0-
#40000000000000
1-
#40500000000000
0-
#41000000000000
1-
#41500000000000
0-
#42000000000000
1-
#42500000000000
0-
#42967017200000
0*
1)
#43000000000000
1-
#43500000000000
0-
#44000000000000
1-
#44500000000000
0-
#45000000000000
1-
#45500000000000
0-
#46000000000000
1-
#46500000000000
0-
#47000000000000
1-
#47500000000000
0-
#48000000000000
1-
#48500000000000
0-
#49000000000000
1-
#49500000000000
0-
#50000000000000
1-
#50500000000000
0-
#51000000000000
1-
#51500000000000
0-
#52000000000000
1-
#52500000000000
0-
#53000000000000
1-
#53353323153689

**Comment by andresmanelli** [comment]
@Fresher14 Indeed, there was a missing assignment for t=0. I think #15 should do it
