### ISSUE TITLE
Merging changes upstream

### ISSUE THREAD

**Issue by nobodywasishere** [Toroid-io/vcd2wavedrom#16]
So a few months ago I created a fork of this repo [here](https://github.com/nobodywasishere/vcd2wavedrom), haphazardly making changes and improving things because I wanted to use this for a class and didn't have time to do them "correctly". As such, I have not thoroughly tested all functionality to verify it still works. I do, however, want to contribute what I can back upstream.

Some of the changes I made include:
- Moving `vcd2wavedrom.py` into a folder called `vcd2wavedrom` and adding an `__init__.py` to turn it into a Python package
- Added significantly more command line configuration options (instead of doing everything from a config file - config file should still work though)
- Switched from Verilog_VCD to vcdvcd, fixing some errors I was running into, and added some documentation on the differences in API

On the `demo-site` branch:
- Created a [demo website](http://blog.eowyn.net/vcd2wavedrom/) that uses Brython to run vcd2wavedrom in a web browser, statically hosted on GitHub pages 
- Turned VCD2Wavedrom into a class so that it could be called from another Python function, instead of from only command line
- The VCD2Wavedrom class can read from a string containing the vcd instead of just a file

Some of the configuration options I put in don't work correctly or as expected, though this was okay for what I was using it for. Come the end of December/beginning of January I may be able to come back to this and rework it all to be more pull-requestable, but I wanted to get your feedback on these changes first to make sure you would be okay with them, and/or like them. These changes should also allow for publishing to pypi after a setup.py is created.

**Comment by andresmanelli** [comment]
Hello, I'm glad this was useful for your classes. I much like everything you did ^^ +100 for the demo website !

I think it could be wise to split the changes in several small PRs:

 - [ ] Moving to vcdvcd
 - [ ] Add command line configurations (one PR per option maybe, to ease reviewing/test )
 - [ ] Creating the python package
 - [ ] Turn the function into a class
 - [ ] Make is possible to read a string
 - [ ] Add the demo-site ?

I'll be happy to review the PRs whenever you have time to do it. Thanks !

**Comment by nobodywasishere** [comment]
While digging deeper into this, I found it important to let you know that Verilog_VCD, and by extension VCDVCD, are both under the Perl 5 License, which is essentially a dual-license between GPLv1+ and the Artistic License. The specific terms of which can be found [here](https://dev.perl.org/licenses/).

**Comment by nobodywasishere** [comment]
That should be everything except for the demo website, which I'm still working on. Obv take your time in reviewing these, and let me know if you run into issues or have questions. Thank you!

**Comment by andresmanelli** [comment]
Well sorry it took so much time, but all is merged, except for that demo website. I'll create a separate issue for the demo website, to keep it around.

Thank you for the contributions !

**Comment by nobodywasishere** [comment]
No worries about the timeframe. Thank you so much!
